
export interface CountryData {
  label: string;
  value: string;
}

export interface OrderByLetterType {
  a: CountryData[]
  b: CountryData[]
  c: CountryData[]
  d: CountryData[]
  e: CountryData[]
  f: CountryData[]
  g: CountryData[]
  h: CountryData[]
  j: CountryData[]
  k: CountryData[]
  l: CountryData[]
  m: CountryData[]
  n: CountryData[]
  p: CountryData[]
  r: CountryData[]
  s: CountryData[]
  t: CountryData[]
  w: CountryData[]
  x: CountryData[]
  y: CountryData[]
  z: CountryData[]
}

export const orderByLetter: OrderByLetterType = {
  "a": [
    {
      "label": "阿尔巴尼亚",
      "value": "al,7"
    },
    {
      "label": "阿尔及利亚",
      "value": "dz,5"
    },
    {
      "label": "阿富汗",
      "value": "af,5"
    },
    {
      "label": "阿根廷",
      "value": "ar,5"
    },
    {
      "label": "爱尔兰",
      "value": "ie,7"
    },
    {
      "label": "埃及",
      "value": "eg,5"
    },
    {
      "label": "埃塞俄比亚",
      "value": "et,5"
    },
    {
      "label": "爱沙尼亚",
      "value": "ee,7"
    },
    {
      "label": "阿拉伯联合酋长国",
      "value": "ae,5"
    },
    {
      "label": "阿鲁巴",
      "value": "aw,5"
    },
    {
      "label": "阿曼",
      "value": "om,5"
    },
    {
      "label": "安道尔",
      "value": "ad,7"
    },
    {
      "label": "安哥拉",
      "value": "ao,5"
    },
    {
      "label": "安圭拉",
      "value": "ai,5"
    },
    {
      "label": "安提瓜和巴布达",
      "value": "ag,5"
    },
    {
      "label": "澳大利亚",
      "value": "au,7"
    },
    {
      "label": "奥地利",
      "value": "at,7"
    },
    {
      "label": "阿塞拜疆",
      "value": "az,5"
    }
  ],
  "b": [
    {
      "label": "巴巴多斯",
      "value": "bb,5"
    },
    {
      "label": "巴布亚新几内亚",
      "value": "pg,5"
    },
    {
      "label": "巴哈马",
      "value": "bs,5"
    },
    {
      "label": "白俄罗斯",
      "value": "by,5"
    },
    {
      "label": "巴基斯坦",
      "value": "pk,5"
    },
    {
      "label": "巴拉圭",
      "value": "py,5"
    },
    {
      "label": "巴勒斯坦",
      "value": "ps,5"
    },
    {
      "label": "巴林",
      "value": "bh,5"
    },
    {
      "label": "巴拿马",
      "value": "pa,5"
    },
    {
      "label": "保加利亚",
      "value": "bg,7"
    },
    {
      "label": "巴西",
      "value": "br,5"
    },
    {
      "label": "北马其顿",
      "value": "mk,7"
    },
    {
      "label": "贝宁",
      "value": "bj,5"
    },
    {
      "label": "比利时",
      "value": "be,7"
    },
    {
      "label": "冰岛",
      "value": "is,7"
    },
    {
      "label": "博茨瓦纳",
      "value": "bw,5"
    },
    {
      "label": "波多黎各",
      "value": "pr,5"
    },
    {
      "label": "波兰",
      "value": "pl,7"
    },
    {
      "label": "玻利维亚",
      "value": "bo,5"
    },
    {
      "label": "伯利兹",
      "value": "bz,5"
    },
    {
      "label": "波斯尼亚和黑塞哥维那",
      "value": "ba,7"
    },
    {
      "label": "布基纳法索",
      "value": "bf,5"
    },
    {
      "label": "布隆迪",
      "value": "bi,5"
    }
  ],
  "c": [
    {
      "label": "赤道几内亚",
      "value": "gq,5"
    }
  ],
  "d": [
    {
      "label": "丹麦",
      "value": "dk,7"
    },
    {
      "label": "德国",
      "value": "de,7"
    },
    {
      "label": "多哥",
      "value": "tg,5"
    },
    {
      "label": "多米尼加共和国",
      "value": "do,5"
    }
  ],
  "e": [
    {
      "label": "厄瓜多尔",
      "value": "ec,5"
    },
    {
      "label": "厄立特里亚",
      "value": "er,5"
    },
    {
      "label": "俄罗斯",
      "value": "ru,8"
    }
  ],
  "f": [
    {
      "label": "法国",
      "value": "fr,7"
    },
    {
      "label": "法罗群岛",
      "value": "fo,7"
    },
    {
      "label": "梵蒂冈",
      "value": "va,7"
    },
    {
      "label": "法属波利尼西亚",
      "value": "pf,5"
    },
    {
      "label": "法属圭亚那",
      "value": "gf,5"
    },
    {
      "label": "斐济",
      "value": "fj,5"
    },
    {
      "label": "菲律宾",
      "value": "ph,5"
    },
    {
      "label": "芬兰",
      "value": "fi,7"
    },
    {
      "label": "佛得角",
      "value": "cv,5"
    }
  ],
  "g": [
    {
      "label": "冈比亚",
      "value": "gm,5"
    },
    {
      "label": "刚果（布）",
      "value": "cg,5"
    },
    {
      "label": "刚果（金）",
      "value": "cd,5"
    },
    {
      "label": "格陵兰岛",
      "value": "gl,7"
    },
    {
      "label": "格林纳达",
      "value": "gd,5"
    },
    {
      "label": "格鲁吉亚",
      "value": "ge,5"
    },
    {
      "label": "哥伦比亚",
      "value": "co,5"
    },
    {
      "label": "哥斯达黎加",
      "value": "cr,5"
    },
    {
      "label": "瓜德罗普",
      "value": "gp,5"
    },
    {
      "label": "圭亚那",
      "value": "gy,5"
    }
  ],
  "h": [
    {
      "label": "海地",
      "value": "ht,5"
    },
    {
      "label": "韩国",
      "value": "kr,5"
    },
    {
      "label": "哈萨克斯坦",
      "value": "kz,5"
    },
    {
      "label": "黑山",
      "value": "me,7"
    },
    {
      "label": "荷兰",
      "value": "nl,7"
    },
    {
      "label": "洪都拉斯",
      "value": "hn,5"
    }
  ],
  "j": [
    {
      "label": "加纳",
      "value": "gh,5"
    },
    {
      "label": "加拿大",
      "value": "ca,7"
    },
    {
      "label": "柬埔寨",
      "value": "kh,5"
    },
    {
      "label": "加蓬",
      "value": "ga,5"
    },
    {
      "label": "吉布提",
      "value": "dj,5"
    },
    {
      "label": "捷克共和国",
      "value": "cz,7"
    },
    {
      "label": "吉尔吉斯斯坦",
      "value": "kg,5"
    },
    {
      "label": "津巴布韦",
      "value": "zw,5"
    },
    {
      "label": "几内亚",
      "value": "gn,5"
    },
    {
      "label": "几内亚比绍",
      "value": "gw,5"
    }
  ],
  "k": [
    {
      "label": "开曼群岛",
      "value": "ky,5"
    },
    {
      "label": "喀麦隆",
      "value": "cm,5"
    },
    {
      "label": "卡塔尔",
      "value": "qa,5"
    },
    {
      "label": "克罗地亚",
      "value": "hr,7"
    },
    {
      "label": "科摩罗",
      "value": "km,5"
    },
    {
      "label": "肯尼亚",
      "value": "ke,5"
    },
    {
      "label": "科特迪瓦",
      "value": "ci,5"
    },
    {
      "label": "科威特",
      "value": "kw,5"
    },
    {
      "label": "库克群岛",
      "value": "ck,5"
    }
  ],
  "l": [
    {
      "label": "莱索托",
      "value": "ls,5"
    },
    {
      "label": "老挝",
      "value": "la,5"
    },
    {
      "label": "拉脱维亚",
      "value": "lv,7"
    },
    {
      "label": "黎巴嫩",
      "value": "lb,5"
    },
    {
      "label": "利比里亚",
      "value": "lr,5"
    },
    {
      "label": "利比亚",
      "value": "ly,5"
    },
    {
      "label": "列支敦士登",
      "value": "li,7"
    },
    {
      "label": "立陶宛",
      "value": "lt,7"
    },
    {
      "label": "留尼汪",
      "value": "re,5"
    },
    {
      "label": "罗马尼亚",
      "value": "ro,7"
    },
    {
      "label": "卢森堡",
      "value": "lu,7"
    },
    {
      "label": "卢旺达",
      "value": "rw,5"
    }
  ],
  "m": [
    {
      "label": "马达加斯加",
      "value": "mg,5"
    },
    {
      "label": "马尔代夫",
      "value": "mv,5"
    },
    {
      "label": "马耳他",
      "value": "mt,7"
    },
    {
      "label": "马来西亚",
      "value": "my,5"
    },
    {
      "label": "马拉维",
      "value": "mw,5"
    },
    {
      "label": "马里",
      "value": "ml,5"
    },
    {
      "label": "毛里求斯",
      "value": "mu,5"
    },
    {
      "label": "毛里塔尼亚",
      "value": "mr,5"
    },
    {
      "label": "马提尼克岛",
      "value": "mq,5"
    },
    {
      "label": "马约特",
      "value": "yt,5"
    },
    {
      "label": "美国",
      "value": "us,7"
    },
    {
      "label": "蒙古",
      "value": "mn,5"
    },
    {
      "label": "孟加拉",
      "value": "bd,5"
    },
    {
      "label": "蒙特塞拉特岛",
      "value": "ms,5"
    },
    {
      "label": "缅甸",
      "value": "mm,5"
    },
    {
      "label": "秘鲁",
      "value": "pe,5"
    },
    {
      "label": "摩尔多瓦",
      "value": "md,7"
    },
    {
      "label": "摩洛哥",
      "value": "ma,5"
    },
    {
      "label": "摩纳哥",
      "value": "mc,7"
    },
    {
      "label": "莫桑比克",
      "value": "mz,5"
    },
    {
      "label": "墨西哥",
      "value": "mx,5"
    }
  ],
  "n": [
    {
      "label": "纳米比亚",
      "value": "na,5"
    },
    {
      "label": "南非",
      "value": "za,5"
    },
    {
      "label": "瑙鲁",
      "value": "nr,5"
    },
    {
      "label": "尼泊尔",
      "value": "np,5"
    },
    {
      "label": "尼加拉瓜",
      "value": "ni,5"
    },
    {
      "label": "尼日尔",
      "value": "ne,5"
    },
    {
      "label": "尼日利亚",
      "value": "ng,5"
    },
    {
      "label": "挪威",
      "value": "no,7"
    }
  ],
  "p": [
    {
      "label": "葡萄牙",
      "value": "pt,7"
    }
  ],
  "r": [
    {
      "label": "日本",
      "value": "jp,5"
    },
    {
      "label": "瑞典",
      "value": "se,7"
    },
    {
      "label": "瑞士",
      "value": "ch,7"
    }
  ],
  "s": [
    {
      "label": "萨尔瓦多",
      "value": "sv,5"
    },
    {
      "label": "塞尔维亚",
      "value": "rs,7"
    },
    {
      "label": "塞拉利昂",
      "value": "sl,5"
    },
    {
      "label": "塞内加尔",
      "value": "sn,5"
    },
    {
      "label": "塞浦路斯",
      "value": "cy,7"
    },
    {
      "label": "塞舌尔",
      "value": "sc,5"
    },
    {
      "label": "沙特阿拉伯",
      "value": "sa,5"
    },
    {
      "label": "圣多美和普林西比",
      "value": "st,5"
    },
    {
      "label": "圣卢西亚",
      "value": "lc,5"
    },
    {
      "label": "圣马力诺",
      "value": "sm,7"
    },
    {
      "label": "斯里兰卡",
      "value": "lk,5"
    },
    {
      "label": "斯洛伐克",
      "value": "sk,7"
    },
    {
      "label": "斯洛文尼亚",
      "value": "si,7"
    },
    {
      "label": "斯威士兰",
      "value": "sz,5"
    },
    {
      "label": "苏里南",
      "value": "sr,5"
    },
    {
      "label": "所罗门群岛",
      "value": "sb,5"
    },
    {
      "label": "索马里",
      "value": "so,5"
    }
  ],
  "t": [
    {
      "label": "泰国",
      "value": "th,5"
    },
    {
      "label": "塔吉克斯坦",
      "value": "tj,5"
    },
    {
      "label": "汤加",
      "value": "to,5"
    },
    {
      "label": "坦桑尼亚",
      "value": "tz,5"
    },
    {
      "label": "特立尼达和多巴哥",
      "value": "tt,5"
    },
    {
      "label": "土耳其",
      "value": "tr,7"
    },
    {
      "label": "土库曼斯坦",
      "value": "tm,5"
    },
    {
      "label": "突尼斯",
      "value": "tn,5"
    }
  ],
  "w": [
    {
      "label": "危地马拉",
      "value": "gt,5"
    },
    {
      "label": "委内瑞拉",
      "value": "ve,5"
    },
    {
      "label": "文莱",
      "value": "bn,5"
    },
    {
      "label": "乌干达",
      "value": "ug,5"
    },
    {
      "label": "乌克兰",
      "value": "ua,7"
    },
    {
      "label": "乌拉圭",
      "value": "uy,5"
    },
    {
      "label": "乌兹别克斯坦",
      "value": "uz,5"
    }
  ],
  "x": [
    {
      "label": "西班牙",
      "value": "es,7"
    },
    {
      "label": "希腊",
      "value": "gr,7"
    },
    {
      "label": "新加坡",
      "value": "sg,5"
    },
    {
      "label": "新西兰",
      "value": "nz,7"
    },
    {
      "label": "匈牙利",
      "value": "hu,7"
    }
  ],
  "y": [
    {
      "label": "牙买加",
      "value": "jm,5"
    },
    {
      "label": "亚美尼亚",
      "value": "am,5"
    },
    {
      "label": "也门",
      "value": "ye,5"
    },
    {
      "label": "意大利",
      "value": "it,7"
    },
    {
      "label": "伊拉克",
      "value": "iq,5"
    },
    {
      "label": "印度",
      "value": "in,5"
    },
    {
      "label": "印度尼西亚",
      "value": "id,5"
    },
    {
      "label": "英国",
      "value": "gb,7"
    },
    {
      "label": "英属维尔京群岛",
      "value": "vg,5"
    },
    {
      "label": "以色列",
      "value": "il,7"
    },
    {
      "label": "约旦",
      "value": "jo,5"
    },
    {
      "label": "越南",
      "value": "vn,5"
    }
  ],
  "z": [
    {
      "label": "赞比亚",
      "value": "zm,5"
    },
    {
      "label": "乍得",
      "value": "td,5"
    },
    {
      "label": "直布罗陀",
      "value": "gi,7"
    },
    {
      "label": "智利",
      "value": "cl,5"
    },
    {
      "label": "中非共和国",
      "value": "cf,5"
    },
    {
      "label": "中国",
      "value": "cn,1"
    },
    {
      "label": "中国澳门",
      "value": "mo,5"
    },
    {
      "label": "中国台湾",
      "value": "tw,5"
    },
    {
      "label": "中国香港",
      "value": "hk,5"
    }
  ]
}